apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kafka
      - strimzi
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: metrics
    interval: 15s
