apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-perf-test
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: kafka-producer-perf-test
        image: quay.io/strimzi/kafka:0.36.1-kafka-3.5.1
        command:
        - "/bin/bash"
        - "-c"
        - "/opt/kafka/bin/kafka-producer-perf-test.sh --topic topic-one --num-records 100000 --record-size 100 --throughput 1000 --producer-props bootstrap.servers=kafka-cluster-kafka-bootstrap:9092"
      restartPolicy: Never
